#!/bin/bash
####################################
# All rights reserved.              #
# started from Zero                 #
# Docker owned dockserver           #
# Docker Maintainer dockserver      #
#####################################
#####################################
# THE DOCKER ARE UNDER LICENSE      #
# NO CUSTOMIZING IS ALLOWED         #
# NO REBRANDING IS ALLOWED          #
# NO CODE MIRRORING IS ALLOWED      #
#####################################
# shellcheck disable=SC2086
# shellcheck disable=SC2006
if [[ $EUID != 0 ]]; then
    sudo "$0" "$@"
    exit $?
fi
dockserver=/opt/dockserver
run() {
if [[ -d ${dockserver} ]];then
   cd ${dockserver} && $(command -v bash) install.sh
else
   usage
fi
}
####
update() {
dockserver=/opt/dockserver
clear
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "    🚀    DockServer [ UPDATE ] STARTED"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    basefolder="/opt/appdata"
    compose="compose/docker-compose.yml"
    ds=$(docker ps -aq --format '{{.Names}}' | sed '/^$/d' | grep -v 'trae' | grep -x 'dockserver')
    if [[ $ds != 'dockserver' ]];then
       $(command -v rsync) ${dockserver}/dockserver/docker.yml $basefolder/$compose -aqhv;fi
       if [[ -f $basefolder/$compose ]];then
          $(command -v cd) $basefolder/compose/
          docker-compose config 1>/dev/null 2>&1
          errorcode=$?
          if [[ $errorcode -eq 0 ]];then
             docker-compose up -d --force-recreate 1>/dev/null 2>&1
          fi
    else
       $(command -v docker) restart dockserver 1>/dev/null 2>&1
    fi
    $(command -v chown) -cR 1000:1000 ${dockserver} 1>/dev/null 2>&1
    clear
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "    🚀    DockServer [ UPDATE ] DONE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
}
####
dev() {
dockserver=/opt/dockserver
clear
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "    🚀    DockServer [ DEV - CLONING ] STARTED"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
     $(command -v rm) -rf ${dockserver}
     git clone --quiet -b dev https://github.com/dockserver/dockserver.git ${dockserver}
     $(command -v chown) -cR 1000:1000 ${dockserver} 1>/dev/null 2>&1
     envmigra && clear
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "    🚀    DockServer [ DEV - CLONING ] DONE"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
}
####
fork() {
dockserver=/opt/dockserver
DOCK=${DOCK}
FORK=${FORK}
if [[ ${DOCK} == "-f" || ${DOCK} == "--fork" ]];then
   if [[ ${FORK} != "" ]];then
       if [[ -d ${dockserver} ]];then
clear
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "    🚀    DockServer FORK Version Pull started"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
     $(command -v rm) -rf ${dockserver}
     git clone --quiet ${FORK} ${dockserver}
     $(command -v chown) -cR 1000:1000 ${dockserver} 1>/dev/null 2>&1
     envmigra
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "    🚀    DockServer FORK Version Pull finished"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
       fi
   fi
fi
clear
}
usage() {
clear
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "    🚀    DockServer [ USAGE COMMANDS ]"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo ""
echo "   Commands :"
echo ""
echo "   dockserver -i / --install     =   open the dockserver setup"
echo "   dockserver -h / --help        =   help/usage"
echo "   dockserver -u / --update      =   update the local dockserver edition"
echo ""
echo "   dockserver -d / --dev         =   clone the dev branch of dockserver"
echo "   dockserver -f / --fork <link> =   run you own repo"
echo ""
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
echo "    🚀    DockServer [ USAGE COMMANDS ]"
echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"

}
envmigra() {
basefolder="/opt/appdata"
envmigrate="$basefolder/apps/.subactions/envmigrate.sh
if [[ -f "$basefolder/compose/.env" ]] 
   $(command -v bash) $envmigrate
fi 
}

DOCK=$1
FORK=$2
case "$DOCK" in
 "" ) envmigra && run ;;
 "-i" ) envmigra && run ;;
 "--install" ) envmigra && run ;;
 "-u" ) update ;;
 "--update" ) update ;;
 "-h" ) usage ;;
 "--help" ) usage ;;
 "-d" ) envmigra && dev ;;
 "--dev" ) envmigra && dev ;;
 "-f" ) envmigra && fork ;;
 "--fork" ) envmigra && fork ;;
esac
#EOF
