version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "daily"
    rebase-strategy: "auto"
    target-branch: "master"
    labels:
      - "dependabot"
    open-pull-requests-limit: 10
    commit-message:
      prefix: "GH updates "
      prefix-development: "GH dev"
      include: "scope"

