daysUntilStale: 7
daysUntilClose: 7
exemptLabels:
- on-hold
- pinned

staleLabel: stale

issues:
  markComment: >
    This Issue has been automatically marked as "stale" because it has not had recent activity (for 7 days). It will be closed if no further activity occurs. Thanks for the feedback.
  closeComment: >
    Due to the lack of activity in the last 7 days since it was marked as "stale", we proceed to close this Issue. Do not hesitate to reopen it later if necessary.
pulls:
  markComment: >
    This Pull Request has been automatically marked as "stale" because it has not had recent activity (for 7 days). It will be closed if no further activity occurs. Thank you for your contribution.
  closeComment: >
    Due to the lack of activity in the last 5 days since it was marked as "stale", we proceed to close this Pull Request. Do not hesitate to reopen it later if necessary.

limitPerRun: 30
