---
version: '3'
services:
  mount:
    cap_add:
      - 'SYS_ADMIN'
    container_name: 'mount'
    hostname: 'mount'
    privileged: 'true'
    devices:
      - '/dev/fuse:/dev/fuse'
    environment:
      - 'PGID=${ID}'
      - 'PUID=${ID}'
      - 'TZ=${TZ}'
    image: 'ghcr.io/dockserver/docker-mount:dockserver'
    restart: '${RESTARTAPP}'
    networks:
      - proxy
    security_opt:
      - 'apparmor:unconfined'
      - 'no-new-privileges:true'
    volumes:
      - '/etc/localtime:/etc/localtime:ro'
      - '${APPFOLDER}/system:/system:rshared'
      - '/mnt:/mnt:shared'
networks:
  proxy:
    driver: bridge
    external: true
