---
version: "3"
services:
  mount:
    container_name: "mount"
    hostname: "mount"
    privileged: true
    environment:
      - "PGID=${ID}"
      - "PUID=${ID}"
      - "TZ=${TZ}"
    image: "ghcr.io/dockserver/docker-mount:latest"
    restart: "${RESTARTAPP}"
    networks:
      - ${DOCKERNETWORK}
    security_opt:
      - "apparmor:unconfined"
      - "${SECURITYOPS}:${SECURITYOPSSET}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${APPFOLDER}/system:/system:rshared"
      - "/mnt:/mnt:shared"
    labels:
      - "dockupdater.disable=true"
      - "com.centurylinklabs.watchtower.enable=false"
networks:
  proxy:
    driver: bridge
    external: true
