---
version: "3.9"
## SET GLOBAL HEADER FOR COMPOSER
services:
  mount:
    cap_add:
      - "SYS_ADMIN"
    container_name: "mount"
    hostname: "mount"
    privileged: true
    devices:
      - "/dev/fuse:/dev/fuse"
    environment:
      - "PGID=${ID}"
      - "PUID=${ID}"
      - "TZ=${TZ}"
    image: "ghcr.io/dockserver/docker-mount:latest"
    restart: "${RESTARTAPP}"
    networks:
      - ${DOCKERNETWORK}
    security_opt:
      - "apparmor:unconfined"
      - "${SECURITYOPS}:${SECURITYOPSSET}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${APPFOLDER}/system:/system:rshared"
      - "/mnt:/mnt:shared"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "dockupdater.enable=false"
      - "traefik.http.routers.mount-rtr.entrypoints=https"
      - "traefik.http.routers.mount-rtr.rule=Host(`mount.${DOMAIN}`)"
      - "traefik.http.routers.mount-rtr.tls=true"
      - "traefik.http.routers.mount-rtr.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.mount-rtr.middlewares=chain-authelia@file"
      - "traefik.http.routers.mount-rtr.service=mount-svc"
      - "traefik.http.services.mount-svc.loadbalancer.server.port=8554"
networks:
  proxy:
    driver: bridge
    external: true
