---
version: "3"
services:
  cloudflared:
    image: "ghcr.io/crazy-max/cloudflared"
    hostname: "cloudflared"
    container_name: "cloudflared"
    ports:
      - "${PORTBLOCK}:5053:5053/udp" #Donot expose this publicly on a remote server, only use VPN
      - "${PORTBLOCK}:49312:49312/tcp"
    networks:
      - ${DOCKERNETWORK}
    environment:
      - "PGID=${ID}"
      - "PUID=${ID}"
      - "TZ=${TZ}"
      - "TUNNEL_DNS_UPSTREAM=https://1.1.1.1/dns-query,https://1.0.0.1/dns-query"
      - "TUNNEL_DNS_ADDRESS=0.0.0.0" #This should not be changed unless you know what you are doing
      - "TUNNEL_DNS_PORT=5053" #This should not be changed unless you know what you are doing
      - "TUNNEL_METRICS=0.0.0.0:49312" #This should not be changed unless you know what you are doing
    labels:
      - "dockupdater.enable=true"
    restart: "${RESTARTAPP}"
networks:
  proxy:
    driver: bridge
    external: true
