---
version: "3"
services:
  mongodb:
    container_name: "mongodb"
    hostname: "mongodb"
    environment:
      - "PGID=${ID}"
      - "PUID=${ID}"
      - "TZ=${TZ}"
      - "UMASK=${UMASK}"
      - "MONGO_INITDB_ROOT_USERNAME=${MONGO_INITDB_ROOT_USERNAME}"
      - "MONGO_INITDB_ROOT_PASSWORD=${MONGO_INITDB_ROOT_PASSWORD}"
    image: "mongo:latest"
    restart: "${RESTARTAPP}"
    ports:
      - "${PORTBLOCK}:27017:27017"
    networks:
      - ${DOCKERNETWORK}
    security_opt:
      - "${SECURITYOPS}:${SECURITYOPSSET}"
    volumes:
      - "${APPFOLDER}/mongodb:/data/db:rw"
    labels:
      - "dockupdater.enable=true"
networks:
  proxy:
    driver: bridge
    external: true