---
version: '3'
services:  
  pihole:
    image: pihole/pihole
    hostname: pihole
    container_name: pihole
#TIP: Just replace ${PORTBLOCK} with your servers VPN IP to set this up.
    ports:
      - ${PORTBLOCK}:446:443
      - ${PORTBLOCK}:8008:80
      - ${PORTBLOCK}:53:53 #Donot expose this publicly on a remote server, only use VPN
      - ${PORTBLOCK}:53:53/udp #Donot expose this publicly on a remote server, only use VPN
      - ${PORTBLOCK}:67:67/udp
    cap_add:
      - NET_ADMIN
    networks:
      - proxy
    dns:
      - 127.0.0.1
      - 1.1.1.1
      - 8.8.8.8
    environment:
      - 'PGID=${ID}'
      - 'PUID=${ID}'
      - 'PIHOLE_DNS_=${PORTBLOCK}#5053;${PORTBLOCK}#5053' #Unbound DNS, Set this to Cloudflare or Google etc if not using Unbound.
      - 'ServerIP=${PORTBLOCK}'
      - 'TZ=${TZ}'
      - 'WEBPASSWORD=WEBPASSWORD'
      - 'DNSSEC=true'
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APPFOLDER}/pihole/dnsmasq.d:/etc/dnsmasq.d
      - ${APPFOLDER}/pihole:/etc/pihole
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=proxy'
      - 'dockupdater.enable=true'
      - 'traefik.http.routers.pihole-rtr.entrypoints=https'
      - 'traefik.http.routers.pihole-rtr.rule=Host(`pihole.${DOMAIN}`)'
      - 'traefik.http.routers.pihole-rtr.tls=true'
      - 'traefik.http.routers.pihole-rtr.tls.certresolver=dns-cloudflare'
      - 'traefik.http.routers.pihole-rtr.middlewares=chain-authelia@file'
      - 'traefik.http.routers.pihole-rtr.service=pihole-svc'
      - 'traefik.http.services.pihole-svc.loadbalancer.server.port=80'
networks:
  proxy:
    driver: bridge
    external: true
