---
version: '3'
services:  
  pihole:
    hostname: pihole
    container_name: pihole
    image: cbcrowe/pihole-unbound:latest
    ports:
      - '${PORTBLOCK}:446:443/tcp' 
      - '${PORTBLOCK}:53:53/tcp' #Donot expose this publicly on a remote server, Use WireGuard/Tailscale VPN 
      - '${PORTBLOCK}:53:53/udp' #Donot expose this publicly on a remote server, Use WireGuard/Tailscale VPN
      - '${PORTBLOCK}:8008:80/tcp'
    cap_add:
      - NET_ADMIN
    networks:
      - proxy
    dns:
      - 127.0.0.1
      - 1.1.1.1
      - 8.8.8.8
    environment:
      - 'PGID=${ID}'
      - 'PUID=${ID}'
      - 'DNS1=127.0.0.1#5335' #Unbound DNS
      - 'DNS2=127.0.0.1#5335' #Unbound DNS
      - 'ServerIP=${PORTBLOCK}' #Donot expose this publicly on a remote server, Use WireGuard/Tailscale VPN 
      - 'TZ=${TZ}'
      - 'WEBPASSWORD=WEBPASSWORD'
      - 'DNSSEC=true'
    restart: unless-stopped
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - ${APPFOLDER}/pihole/dnsmasq.d:/etc/dnsmasq.d
      - ${APPFOLDER}/pihole/pihole:/etc/pihole
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=proxy'
      - 'dockupdater.enable=true'
      - 'traefik.http.routers.pihole-rtr.entrypoints=https'
      - 'traefik.http.routers.pihole-rtr.rule=Host(`pihole.${DOMAIN}`)'
      - 'traefik.http.routers.pihole-rtr.tls=true'
      - 'traefik.http.routers.pihole-rtr.tls.certresolver=dns-cloudflare'
      - 'traefik.http.routers.pihole-rtr.middlewares=chain-authelia@file'
      - 'traefik.http.routers.pihole-rtr.service=pihole-svc'
      - 'traefik.http.services.pihole-svc.loadbalancer.server.port=80'
networks:
  proxy:
    driver: bridge
    external: true
