---
version: "3.9"
services:
  gluetun:
    hostname: "gluetun"
    container_name: "gluetun"
    image: "qmcgaw/gluetun:latest"
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    restart: "${RESTARTAPP}"
    extra_hosts:
      - "analytics.plex.tv:127.0.0.1"
      - "metrics.plex.tv:127.0.0.1"
      - "metric.plex.tv:127.0.0.1"
      - "mf.svc.nhl.com:127.0.0.1"
      - "mlb-ws-mf.media.mlb.com:127.0.0.1"
      - "playback.svcs.mlb.com:127.0.0.1"
    networks:
      - ${DOCKERNETWORK}
    environment:
      - "PUID=${ID}"
      - "PGID=${ID}"
      - "TZ=${TZ}"
      - "UMASK=${UMASK}"
      - "VPN_SERVICE_PROVIDER=${GLUETUN_VPN_SERVICE_PROVIDER}"
      - "VPN_TYPE=${GLUETUN_VPN_TYPE}"
      - "OPENVPN_USER=${GLUETUN_OPEN_VPN_USER}"
      - "OPENVPN_PASSWORD=${GLUETUN_OPEN_VPN_PASSWORD}"
      - "REGION=${GLUETUN_VPN_REGION}"
      - "SHADOWSOCKS=on"
      - "SHADOWSOCKS_ADDRESS=:8388"
      - "HTTPPROXY=on"
      - "HTTPPROXY_LISTENING_ADDRESS=:8888"
    volumes:
      - "${APPFOLDER}/gluetun/:/gluetun:rw"
    labels:
      - "dockupdater.disable=true"
  plex:
    hostname: "plex"
    container_name: "plex"
    environment:
      - "PGID=${ID}"
      - "PUID=${ID}"
      - "TZ=${TZ}"
      - "UMASK=${UMASK}"
      - "PLEX_CLAIM=PLEX_CLAIM_ID"
      - "VERSION=${PLEXVERSION}"
      - "ADVERTISE_IP=https://plex.${DOMAIN}:443"
      - "DOCKER_MODS=ghcr.io/gilbn/theme.park:plex|ghcr.io/dockserver/docker-mod-healthcheck:latest"
      - "TP_THEME=${PLEXTHEME}"
      - "TP_ADDON=${PLEXADDON}"
    image: "${PLEXIMAGE}"
    restart: "${RESTARTAPP}"
    depends_on: gluetun
    network_mode: "container:gluetun"
    security_opt:
      - "${SECURITYOPS}:${SECURITYOPSSET}"
    volumes:
      - "/etc/localtime:/etc/localtime:ro"
      - "${APPFOLDER}/plex/database:/config:rw"
      - "unionfs:/mnt:ro"
      - "/dev/shm:/ram_transcode:rw"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "dockupdater.enable=true"
      - "traefik.http.routers.plex-rtr.entrypoints=https"
      - "traefik.http.routers.plex-rtr.rule=Host(`plex.${DOMAIN}`)"
      - "traefik.http.routers.plex-rtr.tls=true"
      - "traefik.http.routers.plex-rtr.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.plex-rtr.middlewares=chain-authelia@file"
      - "traefik.http.routers.plex-rtr.service=plex-svc"
      - "traefik.http.services.plex-svc.loadbalancer.server.scheme=https"
      - "traefik.http.services.plex-svc.loadbalancer.server.port=32400"
networks:
  proxy:
    driver: bridge
    external: true
volumes:
  unionfs:
    driver: local-persist
    driver_opts:
      mountpoint: /mnt
