#!/usr/bin/env ansible-playbook
#
# Title:      LXC Bypass the mount :shared
# OS Branch:  ubuntu,debian,rasbian
# Author(s):  mrdoob
# Coauthor:   DrAgOn141
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  name: LXC Playbook
  tasks:
    - cron:
        name: LXC Bypass the mount :shared
        special_time: 'reboot'
        user: root
        job: '/bin/bash /home/.lxcstart.sh 1>/dev/null 2>&1'
        state: present
      become_user: root
      ignore_errors: yes

