---
version: '3'
services:
  davos:
    hostname: 'davos'
    container_name: 'davos'
    environment:
      - 'PGID=${ID}'
      - 'PUID=${ID}'
      - 'TZ=${TZ}'
      - 'UMASK=${UMASK}'
      - 'PASSWORD=${DAVOS_PASSWORD}'
    image: 'ghcr.io/linuxserver/davos'
    restart: '${RESTARTAPP}'
    ports:
      - '${PORTBLOCK}:8088:8080'
    networks:
      - proxy
    security_opt:
      - 'no-new-privileges:true'
    volumes:
      - '${APPFOLDER}/davos:/config:rw'
      - 'unionfs:/mnt'
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=proxy'
      - 'dockupdater.enable=true'
      - 'traefik.http.routers.davos-rtr.entrypoints=https'
      - 'traefik.http.routers.davos-rtr.rule=Host(`davos.${DOMAIN}`)'
      - 'traefik.http.routers.davos-rtr.tls=true'
      - 'traefik.http.routers.davos-rtr.tls.certresolver=dns-cloudflare'
      - 'traefik.http.routers.davos-rtr.middlewares=chain-authelia@file'
      - 'traefik.http.routers.davos-rtr.service=davos-svc'
      - 'traefik.http.services.davos-svc.loadbalancer.server.port=8080'
networks:
  proxy:
    driver: bridge
    external: true
volumes:
  unionfs:
    driver: local-persist
    driver_opts:
      mountpoint: /mnt
