---
version: '3'
services:
  jdownloader2:
    hostname: 'jdownloader2'
    container_name: 'jdownloader2'
    environment:
      - 'USER_ID=${ID}'
      - 'GROUP_ID=${ID}'
      - 'TZ=${TZ}'
      - 'UMASK=${UMASK}'
      - 'APP_NICENESS=1'
      - 'CLEAN_TMP_DIR=1'
      - 'DISPLAY_WIDTH=1920'
      - 'DISPLAY_HEIGHT=1024'
      - 'SECURE_CONNECTION=1'
    image: 'jlesage/jdownloader-2'
    restart: '${RESTARTAPP}'
    cap_add:
      - 'SYS_NICE'
    ports:
      - '${PORTBLOCK}:5800:5800'
      - '${PORTBLOCK}:3219:3129'
    networks:
    networks:
      - proxy
    security_opt:
      - 'no-new-privileges:true'
    volumes:
      - '${APPFOLDER}/jdownloader2:/config:rw'
      - 'unionfs:/mnt'
      - '/mnt/downloads/jdownloader2/:/output:rw'
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=proxy'
      - 'dockupdater.enable=true'
      - 'traefik.http.routers.jdownloader2-rtr.entrypoints=https'
      - 'traefik.http.routers.jdownloader2-rtr.rule=Host(`jdownloader2.${DOMAIN}`)'
      - 'traefik.http.routers.jdownloader2-rtr.tls=true'
      - 'traefik.http.routers.jdownloader2-rtr.tls.certresolver=dns-cloudflare'
      - 'traefik.http.routers.jdownloader2-rtr.middlewares=chain-authelia@file'
      - 'traefik.http.routers.jdownloader2-rtr.service=jdownloader2-svc'
      - 'traefik.http.services.jdownloader2-svc.loadbalancer.server.port=5800'
networks:
  proxy:
    driver: bridge
    external: true
volumes:
  unionfs:
    driver: local-persist
    driver_opts:
      mountpoint: /mnt
