---
version: '3'
services:
  nzbhydra:
    hostname: 'nzbhydra'
    container_name: 'nzbhydra'
    environment:
      - 'PGID=${ID}'
      - 'PUID=${ID}'
      - 'TZ=${TZ}'
      - 'UMASK=${UMASK}'
    image: 'ghcr.io/linuxserver/nzbhydra2'
    restart: '${RESTARTAPP}'
    ports:
      - '${PORTBLOCK}:5076:5076'
    networks:
      - proxy
    security_opt:
      - 'no-new-privileges:true'
    volumes:
      - '${APPFOLDER}/nzbhydra:/config:rw'
      - 'unionfs:/mnt'
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=proxy'
      - 'dockupdater.enable=true'
      - 'traefik.http.routers.nzbhydra2-rtr.entrypoints=https'
      - 'traefik.http.routers.nzbhydra2-rtr.rule=Host(`nzbhydra.${DOMAIN}`)'
      - 'traefik.http.routers.nzbhydra2-rtr.tls=true'
      - 'traefik.http.routers.nzbhydra2-rtr.tls.certresolver=dns-cloudflare'
      - 'traefik.http.routers.nzbhydra2-rtr.middlewares=chain-authelia@file'
      - 'traefik.http.routers.nzbhydra2-rtr.service=nzbhydra2-svc'
      - 'traefik.http.services.nzbhydra2-svc.loadbalancer.server.port=5076'
networks:
  proxy:
    driver: bridge
    external: true
volumes:
  unionfs:
    driver: local-persist
    driver_opts:
      mountpoint: /mnt
