---
version: '3'
services:
  sabnzbd:
    hostname: 'sabnzbd'
    container_name: 'sabnzbd'
    environment:
      - 'PGID=${ID}'
      - 'PUID=${ID}'
      - 'TZ=${TZ}'
      - 'UMASK=${UMASK}'
      - 'DOCKER_MODS=ghcr.io/gilbn/theme.park:sabnzbd'
      - 'TP_THEME=${SABNZBDTHEME}'
    image: '${SABNZBDIMAGE}'
    restart: '${RESTARTAPP}'
    ports:
      - '${PORTBLOCK}:8010:8080'
    networks:
            proxy:
                ipv4_address: 172.18.0.136
    security_opt:
      - 'no-new-privileges:true'
    volumes:
      - '${APPFOLDER}/sabnzbd:/config:rw'
      - 'unionfs:/mnt'
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=proxy'
      - 'dockupdater.enable=true'
      - 'traefik.http.routers.sabnzbd-rtr.entrypoints=https'
      - 'traefik.http.routers.sabnzbd-rtr.rule=Host(`sabnzbd.${DOMAIN}`)'
      - 'traefik.http.routers.sabnzbd-rtr.tls=true'
      - 'traefik.http.routers.sabnzbd-rtr.tls.certresolver=dns-cloudflare'
      - 'traefik.http.routers.sabnzbd-rtr.middlewares=chain-authelia@file'
      - 'traefik.http.routers.sabnzbd-rtr.service=sabnzbd-svc'
      - 'traefik.http.services.sabnzbd-svc.loadbalancer.server.port=8080'
networks:
  proxy:
    driver: bridge
    external: true
volumes:
  unionfs:
    driver: local-persist
    driver_opts:
      mountpoint: /mnt