---
version: "3"
services:
  overseerr:
    hostname: "overseerr"
    container_name: "overseerr"
    environment:
      - "PGID=${ID}"
      - "PUID=${ID}"
      - "TZ=${TZ}"
    image: "ghcr.io/dockserver/docker-overseerr:latest"
    restart: "${RESTARTAPP}"
    networks:
      - ${DOCKERNETWORK}
    security_opt:
      - "${SECURITYOPS}:${SECURITYOPSSET}"
    volumes:
      - "${APPFOLDER}/overseerr:/config:rw"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "dockupdater.enable=true"
      - "traefik.http.routers.overseerr-rtr.entrypoints=https"
      - "traefik.http.routers.overseerr-rtr.rule=Host(`overseerr.${DOMAIN}`)"
      - "traefik.http.routers.overseerr-rtr.tls=true"
      - "traefik.http.routers.overseerr-rtr.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.overseerr-rtr.middlewares=chain-authelia@file"
      - "traefik.http.routers.overseerr-rtr.service=overseerr-svc"
      - "traefik.http.services.overseerr-svc.loadbalancer.server.port=5055"
networks:
  proxy:
    driver: bridge
    external: true
