---
version: "3"
services:
  invitarr:
    hostname: "invitarr"
    container_name: "invitarr"
    environment:
      - "PGID=${ID}"
      - "PUID=${ID}"
      - "TZ=${TZ}"
      - "UMASK=${UMASK}"
      - "token=${Discord_bot_token}"
    image: "piratify/invitarr:latest"
    restart: "${RESTARTAPP}"
    networks:
      - "${DOCKERNETWORK}"
    security_opt:
      - "${SECURITYOPS}:${SECURITYOPSSET}"
    volumes:
      - "${APPFOLDER}/invitarr:/app/app/config"
      - "${LOCALTIME}:${LOCALTIME}:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=${DOCKERNETWORK}"
      - "dockupdater.enable=true"
      - "traefik.http.routers.invitarr-rtr.entrypoints=https"
      - "traefik.http.routers.invitarr-rtr.rule=Host(`invitarr.${DOMAIN}`)"
      - "traefik.http.routers.invitarr-rtr.tls=true"
      - "traefik.http.routers.invitarr-rtr.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.invitarr-rtr.middlewares=chain-authelia@file"
      - "traefik.http.routers.invitarr-rtr.service=invitarr-svc"
      - "traefik.http.services.invitarr-svc.loadbalancer.server.port=5001"
networks:
  proxy:
    driver: bridge
    external: true
