---
version: "3"
services:
  rollarr:
    hostname: "rollarr"
    container_name: "rollarr"
    environment:
      - "PGID=${ID}"
      - "PUID=${ID}"
      - "TZ=${TZ}"
      - "UMASK=${UMASK}"
    image: "ghcr.io/dockserver/docker-rollarr:latest"
    restart: "${RESTARTAPP}"
    networks:
      - ${DOCKERNETWORK}
    security_opt:
      - "${SECURITYOPS}:${SECURITYOPSSET}"
    volumes:
      - "${APPFOLDER}/rollarr/config:/config:rw"
      - "${APPFOLDER}/rollarr/preroll:/config/preroll:rw"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - 'dockupdater.enable=true'
      - "traefik.http.routers.rollarr-rtr.entrypoints=https"
      - "traefik.http.routers.rollarr-rtr.rule=Host(`rollarr.${DOMAIN}`)"
      - "traefik.http.routers.rollarr-rtr.tls=true"
      - "traefik.http.routers.rollarr-rtr.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.rollarr-rtr.middlewares=chain-authelia@file"
      - "traefik.http.routers.rollarr-rtr.service=rollarr-svc"
      - "traefik.http.services.rollarr-svc.loadbalancer.server.port=3100"

networks:
  proxy:
    driver: bridge
    external: true
