---
version: '3'
services:
  unpackerr:
    hostname: 'unpackerr'
    container_name: 'unpackerr'
    environment:
      - 'PGID=${ID}'
      - 'PUID=${ID}'
      - 'TZ=${TZ}'
      # General config
      - 'UN_DEBUG=false'
      - 'UN_LOG_FILE=None'
      - 'UN_LOG_FILES=10'
      - 'UN_LOG_FILE_MB=10'
      - 'UN_INTERVAL=2m'
      - 'UN_START_DELAY=1m'
      - 'UN_RETRY_DELAY=5m'
      - 'UN_MAX_RETRIES=3'
      - 'UN_PARALLEL=1'
      - 'UN_FILE_MODE=0644'
      - 'UN_DIR_MODE=0755'
      # Sonarr Config
      - 'UN_SONARR_0_URL=http://sonarr:8989'
      - 'UN_SONARR_0_API_KEY==NULL'
      - 'UN_SONARR_0_PATHS_0=/mnt/downloads/torrent'
      - 'UN_SONARR_0_PROTOCOLS=torrent'
      - 'UN_SONARR_0_TIMEOUT=10s'
      - 'UN_SONARR_0_DELETE_ORIG=false'
      - 'UN_SONARR_0_DELETE_DELAY=5m'
      # Radarr Config
      - 'UN_RADARR_0_URL=http://radarr:8989#'
      - 'UN_RADARR_0_API_KEY==NULL'
      - 'UN_RADARR_0_PATHS_0=/mnt/downloads/torrent'
      - 'UN_RADARR_0_PROTOCOLS=torrent'
      - 'UN_RADARR_0_TIMEOUT=10s'
      - 'UN_RADARR_0_DELETE_ORIG=false'
      - 'UN_RADARR_0_DELETE_DELAY=5m'
      # Lidarr Config
      - 'UN_LIDARR_0_URL=http://lidarr:8989'
      - 'UN_LIDARR_0_API_KEY=NULL'
      - 'UN_LIDARR_0_PATHS_0=/mnt/downloads/torrent'
      - 'UN_LIDARR_0_PROTOCOLS=torrent'
      - 'UN_LIDARR_0_TIMEOUT=10s'
      - 'UN_LIDARR_0_DELETE_ORIG=false'
      - 'UN_LIDARR_0_DELETE_DELAY=5m'
      # Readarr Config
      - 'UN_READARR_0_URL=http://readarr:8989'
      - 'UN_READARR_0_API_KEY=NULL'
      - 'UN_READARR_0_PATHS_0=/mnt/downloads/torrent'
      - 'UN_READARR_0_PROTOCOLS=torrent'
      - 'UN_READARR_0_TIMEOUT=10s'
      - 'UN_READARR_0_DELETE_ORIG=false'
      - 'UN_READARR_0_DELETE_DELAY=5m'
      # Folder Config
      - 'UN_FOLDER_0_PATH=NULL'
      - 'UN_FOLDER_0_EXTRACT_PATH=NULL'
      - 'UN_FOLDER_0_DELETE_AFTER=10m'
      - 'UN_FOLDER_0_DELETE_ORIGINAL=false'
      - 'UN_FOLDER_0_DELETE_FILES=false'
      - 'UN_FOLDER_0_MOVE_BACK=false'
      # Webhook Config
      - 'UN_WEBHOOK_0_URL=NULL'
      - 'UN_WEBHOOK_0_NAME=NULL'
      - 'UN_WEBHOOK_0_NICKNAME=Unpackerr'
      - 'UN_WEBHOOK_0_CHANNEL=NULL'
      - 'UN_WEBHOOK_0_TIMEOUT='
      - 'UN_WEBHOOK_0_SILENT=false'
      - 'UN_WEBHOOK_0_IGNORE_SSL=false'
      - 'UN_WEBHOOK_0_EXCLUDE=[]'
      - 'UN_WEBHOOK_0_EVENTS=[0]'
      - 'UN_WEBHOOK_0_TEMPLATE_PATH=NULL'
      - 'UN_WEBHOOK_0_CONTENT_TYPE=application/json'
    image: 'ghcr.io/hotio/unpackerr'
    labels:
      - 'dockupdater.enable=true'
    restart: '${RESTARTAPP}'
    networks:
      - proxy
    security_opt:
      - 'no-new-privileges:true'
    volumes:
      - 'unionfs:/mnt'
      - '/etc/localtime:/etc/localtime:ro'
networks:
  proxy:
    driver: bridge
    external: true
volumes:
  unionfs:
    driver: local-persist
    driver_opts:
      mountpoint: /mnt
