#!/bin/ansible-playbook
#
# Title:      deluge Subtask
# Author(s):  MrDoob
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:
    - name: "Set Known Facts"
      set_fact:
        app: "deluge"
        path: "/mnt"
    - name: "Stop {{app}}"
      shell: "docker stop {{app}}"
    - name: "Register Domain"
      shell: cat /etc/hosts | grep 127.0.0.1 | tail -n 1 | awk '{print $2}'
      register: domain
    - name: "Checking for {{app}}/config/core.conf"
      wait_for:
        path: "/opt/appdata/{{app}}/config/core.conf"
        state: present
        delay: 5
    - name: Setting plugins directory
      lineinfile:
        path: "/opt/appdata/{{app}}/config/core.conf"
        regexp: '"plugins_location".*'
        line: '    "plugins_location": "/config/plugins",'
        state: present
    - name: Set move completed location
      lineinfile:
        path: "/opt/appdata/{{app}}/config/core.conf"
        regexp: '"move_completed_path".*'
        line: '    "move_completed_path": "{{path}}/downloads/torrent",'
        state: present
    - name: Set download location
      lineinfile:
        path: "/opt/appdata/{{app}}/config/core.conf"
        regexp: '"download_location".*'
        line: '    "download_location": "{{path}}/incomplete/torrent",'
        state: present
    - name: Setting torrent file directory
      lineinfile:
        path: "/opt/appdata/{{app}}/config/core.conf"
        regexp: '"torrentfiles_location".*'
        line: '    "torrentfiles_location": "{{path}}/torrent/watch",'
        state: present
    - name: Setting torrent watch directory
      lineinfile:
        path: "/opt/appdata/{{app}}/config/core.conf"
        regexp: '"autoadd_location".*'
        line: '    "autoadd_location": "{{path}}/torrent/watch",'
        state: present
    - name: Setting move_completed
      lineinfile:
        path: "/opt/appdata/{{app}}/config/core.conf"
        regexp: '"move_completed".*'
        line: '    "move_completed": true,'
        state: present
    - name: Setting DHT to false
      lineinfile:
        path: "/opt/appdata/{{app}}/config/core.conf"
        regexp: '"dht".*'
        line: '    "dht": false,'
        state: present
    - name: Setting upnp to false
      lineinfile:
        path: "/opt/appdata/{{app}}/config/core.conf"
        regexp: '"upnp".*'
        line: '    "upnp": false,'
        state: present
    #    - name: Setting extractor
    #      lineinfile:
    #        path: '/opt/appdata/{{app}}/config/plugins/extractor.conf'
    #        regexp: '"extract_path".*'
    #        line: '    "extract_path": "{{path}}/downloads/{{app}}"'
    #        state: present
    #- name: set enabled_plugins
    #  replace:
    #    dest: '/opt/appdata/{{app}}/config/core.conf'
    #    regexp: '"enabled_plugins".*'
    #    replace: '"enabled_plugins": ["Extractor", "Label"],'
    - name: set compact_allocation
      lineinfile:
        path: "/opt/appdata/{{app}}/config/core.conf"
        regexp: '"compact_allocation".*'
        line: '    "compact_allocation": true,'
        state: present
    - name: set stop_seed_ratio
      lineinfile:
        path: "/opt/appdata/{{app}}/config/core.conf"
        regexp: '"stop_seed_ratio"".*'
        line: '    "stop_seed_ratio": 1.0,'
        state: present
    - name: set share_ratio_limit
      lineinfile:
        path: "/opt/appdata/{{app}}/config/core.conf"
        regexp: '"share_ratio_limit".*'
        line: '    "share_ratio_limit": 1.0,'
        state: present
    - name: set remove_seed_at_ratio
      lineinfile:
        path: "/opt/appdata/{{app}}/config/core.conf"
        regexp: '"remove_seed_at_ratio".*'
        line: '    "remove_seed_at_ratio": true,'
        state: present
    - name: set enc_prefer_rc4
      lineinfile:
        path: "/opt/appdata/{{app}}/config/core.conf"
        regexp: '"enc_prefer_rc4".*'
        line: '    "enc_prefer_rc4": true,'
        state: present
    - name: set enc_level
      lineinfile:
        path: "/opt/appdata/{{app}}/config/core.conf"
        regexp: '"enc_level".*'
        line: '    "enc_level": 1,'
        state: present
    - name: set enc_in_policy
      lineinfile:
        path: "/opt/appdata/{{app}}/config/core.conf"
        regexp: '"enc_in_policy".*'
        line: '    "enc_in_policy": 1,'
        state: present
    - name: set enc_out_policy
      lineinfile:
        path: "/opt/appdata/{{app}}/config/core.conf"
        regexp: '"enc_out_policy".*'
        line: '    "enc_out_policy": 1,'
        state: present
    - name: set max_active_downloading
      lineinfile:
        path: "/opt/appdata/{{app}}/config/core.conf"
        regexp: '"max_active_downloading".*'
        line: '    "max_active_downloading": 4,'
        state: present
    - name: set dont_count_slow_torrents
      lineinfile:
        path: "/opt/appdata/{{app}}/config/core.conf"
        regexp: '"dont_count_slow_torrents".*'
        line: '    "dont_count_slow_torrents": true,'
        state: present
    - name: set max_active_seeding
      lineinfile:
        path: "/opt/appdata/{{app}}/config/core.conf"
        regexp: '"enabled_plugins".*'
        line: '    "max_active_seeding": 8,'
        state: present
    - name: set share_ratio_limit
      lineinfile:
        path: "/opt/appdata/{{app}}/config/core.conf"
        regexp: '"share_ratio_limit".*'
        line: '    "share_ratio_limit": 1,'
        state: present
    - name: set stop_seed_at_ratio
      lineinfile:
        path: "/opt/appdata/{{app}}/config/core.conf"
        regexp: '"stop_seed_at_ratio".*'
        line: '    "stop_seed_at_ratio": 1.0,'
        state: present
    - name: set seed_time_ratio_limit
      lineinfile:
        path: "/opt/appdata/{{app}}/config/core.conf"
        regexp: '"seed_time_ratio_limit".*'
        line: '    "seed_time_ratio_limit": 1.0,'
        state: present
    - name: "start {{app}}"
      shell: "docker start {{app}}"
