version: "3"
services:
  gluetun:
    hostname: "gluetun"
    container_name: "gluetun"
    image: "qmcgaw/gluetun:latest"
    cap_add:
      - NET_ADMIN
    devices:
      - "/dev/net/tun:/dev/net/tun"
    restart: "${RESTARTAPP}"
    networks:
      - ${DOCKERNETWORK}
    environment:
      - "GID=${ID}"
      - "UID=${ID}"
      - "TZ=${TZ}"
      - "UMASK=${UMASK}"
      - "VPN_SERVICE_PROVIDER=${GLUETUN_VPN_SERVICE_PROVIDER}"
      - "VPN_TYPE=${GLUETUN_VPN_TYPE}"
      - "WIREGUARD_PRIVATE_KEY=${GLUETUN_WG_KEY}"
      - "WIREGUARD_ADDRESSES=${GLUETUN_WG_ADDRESS}"
      - "SERVER_CITIES=${GLUETUN_CITIES}"
      - "SHADOWSOCKS=on"
      - "SHADOWSOCKS_ADDRESS=:8388"
      - "HTTPPROXY=on"
      - "HTTPPROXY_LISTENING_ADDRESS=:8888"
    volumes:
      - "${APPFOLDER}/gluetun/:/gluetun:rw"
  socks5:
    image: "serjs/go-socks5-proxy:latest"
    depends_on:
      - gluetun
    network_mode: "service:gluetun"
networks:
  proxy:
    driver: bridge
    external: true
