---
version: "3"
services:
  netdata:
    container_name: "netdata"
    hostname: "netdata"
    restart: "${RESTARTAPP}"
    image: "netdata/netdata:latest"
    networks:
      - ${DOCKERNETWORK}
    cap_add:
      - "SYS_PTRACE"
    security_opt:
      - "apparmor:unconfined"
    environment:
      - "PGID=${ID}"
      - "PUID=${ID}"
      - "TZ=${TZ}"
      - "UMASK=${UMASK}"
    volumes:
      - "netdataconfig:/etc/netdata"
      - "netdatalib:/var/lib/netdata"
      - "netdatacache:/var/cache/netdata"
      - "/etc/passwd:/host/etc/passwd:ro"
      - "/etc/group:/host/etc/group:ro"
      - "/proc:/host/proc:ro"
      - "/sys:/host/sys:ro"
      - "/etc/os-release:/host/etc/os-release:ro"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "dockupdater.enable=true"
      - "traefik.http.routers.netdata-rtr.entrypoints=https"
      - "traefik.http.routers.netdata-rtr.rule=Host(`netdata.${DOMAIN}`)"
      - "traefik.http.routers.netdata-rtr.tls=true"
      - "traefik.http.routers.netdata-rtr.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.netdata-rtr.middlewares=chain-authelia@file"
      - "traefik.http.routers.netdata-rtr.service=netdata-svc"
      - "traefik.http.services.netdata-svc.loadbalancer.server.port=19999"
volumes:
  netdataconfig:
  netdatalib:
  netdatacache:
networks:
  proxy:
    driver: bridge
    external: true
