---
version: '3.3'
services:
  plex-wrapped:
    hostname: 'plex-wrapped'
    container_name: 'plex-wrapped'
    environment:
      - 'PGID=${ID}'
      - 'PUID=${ID}'
      - 'TZ=${TZ}'
      - 'UMASK=${UMASK}'
    security_opt:
      - "${SECURITYOPS}:${SECURITYOPSSET}"
    image: 'aunefyren/plex-wrapped:latest'
    restart: '${RESTARTAPP}'
    networks:
      - ${DOCKERNETWORK}
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=proxy'
      - 'dockupdater.enable=true'
      - 'traefik.http.routers.plex-wrapped-rtr.entrypoints=https'
      - 'traefik.http.routers.plex-wrapped-rtr.rule=Host(`plex-wrapped.${DOMAIN}`)'
      - 'traefik.http.routers.plex-wrapped-rtr.tls=true'
      - 'traefik.http.routers.plex-wrapped-rtr.tls.certresolver=dns-cloudflare'
      - 'traefik.http.routers.plex-wrapped-rtr.middlewares=chain-no-auth@file'
      - 'traefik.http.routers.plex-wrapped-rtr.service=plex-wrapped-svc'
      - 'traefik.http.services.plex-wrapped-svc.loadbalancer.server.port=80'  
networks:
  proxy:
    driver: bridge
    external: true
