---
version: "3"
services:
  vnstat:
    hostname: "vnstat"
    container_name: "vnstat"
    environment:
      - "PGID=${ID}"
      - "PUID=${ID}"
      - "TZ=${TZ}"
    image: "ghcr.io/dockserver/docker-vnstat:latest"
    networks:
      - ${DOCKERNETWORK}
    restart: "${RESTARTAPP}"
    volumes:
      - "/usr/bin/vnstat:/usr/bin/vnstat"
      - "/var/lib/vnstat:/var/lib/vnstat"
      - "/etc/localtime:/etc/localtime:ro"
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=proxy"
      - "dockupdater.enable=true"
      - "traefik.http.routers.vnstat-rtr.entrypoints=https"
      - "traefik.http.routers.vnstat-rtr.rule=Host(`vnstat.${DOMAIN}`)"
      - "traefik.http.routers.vnstat-rtr.tls=true"
      - "traefik.http.routers.vnstat-rtr.tls.certresolver=dns-cloudflare"
      - "traefik.http.routers.vnstat-rtr.middlewares=chain-authelia@file"
      - "traefik.http.routers.vnstat-rtr.service=vnstat-svc"
      - "traefik.http.services.vnstat-svc.loadbalancer.server.port=80"
networks:
  proxy:
    driver: bridge
    external: true
