---
version: '3'

services:
  sonarrhdr:
    hostname: 'sonarrhdr'
    container_name: 'sonarrhdr'
    environment:
      - 'PGID=${ID}'
      - 'PUID=${ID}'
      - 'TZ=${TZ}'
      - 'UMASK=022'
    image: 'ghcr.io/linuxserver/sonarr:develop'
    restart: 'unless-stopped'
    ports:
      - '127.0.0.1:8985:8989'
    networks:
      - proxy
    security_opt:
      - 'no-new-privileges:true'
    volumes:
      - '/opt/appdata/sonarrhdr:/config:rw'
      - 'unionfs:/mnt'
    labels:
      - 'traefik.enable=true'
      - 'traefik.docker.network=proxy'
      - 'dockupdater.enable=true'
      - 'traefik.http.routers.sonarrhdr-rtr.entrypoints=https'
      - 'traefik.http.routers.sonarrhdr-rtr.rule=Host(`sonarrhdr.${DOMAIN}`)'
      - 'traefik.http.routers.sonarrhdr-rtr.tls=true'
      - 'traefik.http.routers.sonarrhdr-rtr.tls.certresolver=dns-cloudflare'
      - 'traefik.http.routers.sonarrhdr-rtr.middlewares=chain-authelia@file'
      - 'traefik.http.routers.sonarrhdr-rtr.service=sonarrhdr-svc'
      - 'traefik.http.services.sonarrhdr-svc.loadbalancer.server.port=8989'

networks:
  proxy:
    driver: bridge
    external: true

volumes:
  unionfs:
    driver: local-persist
    driver_opts:
      mountpoint: /mnt
