name: SL Scan

on:
  push:
    branches:
    - "*"
  page_build:
  pull_request:
    branches:
    - "*"
  schedule:
    - cron: '* */12 * * *'

jobs:
  Scan-Build:
    runs-on: ubuntu-latest
    steps:
    - uses: step-security/harden-runner@63c24ba6bd7ba022e95695ff85de572c04a18142 # v2
      with:
        egress-policy: block
        disable-telemetry: true
        allowed-endpoints: >
          api.github.com:443
          github.com:443

    - uses: actions/checkout@v4.1.3

    - name: Perform Scan
      uses: ShiftLeftSecurity/scan-action@master
      env:
        WORKSPACE: ""
        GITHUB_TOKEN: ${{ secrets.CR_PAT }}
        SCAN_AUTO_BUILD: true
      with:
        output: reports
        type: composer,shell

    - name: Upload report
      uses: github/codeql-action/upload-sarif@v3
      with:
        sarif_file: reports
